### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by trotor-mml** [opengisch/libqfieldsync#67]
Found this today while debugging database related issue; DeprecationWarning: QgsVectorFileWriter.writeAsVectorFormatV2() is deprecated

That is found in \python\plugins\qfieldsync\libqfieldsync.whl\libqfieldsync\layer.py:810

Is that still relevant warning?

**Comment by m-kuhn** [comment]
Fixed in https://github.com/opengisch/libqfieldsync/pull/92
