### ISSUE TITLE
When exporting a project, the atlas settings are lost

### ISSUE THREAD

**Issue by suricactus** [opengisch/libqfieldsync#7]
```
        <Atlas
        coverageLayerName="Fields"
             coverageLayer="ogr_dbname___home_marco_dev_QField_demo_projects_citybees_new_gpkg__table__area___geom__sql__ba518f87_384f_494b_acd8_66843717f48b"
        enabled="1"
        coverageLayerProvider="ogr"
        pageNameExpression=""
        filterFeatures="0"
        coverageLayerSource="C:/Users/lunic/Documents/01_opengis/dev/QField/resources/demo_projects/bees.gpkg|layername=area"
        sortFeatures="0"
        filenamePattern="'output_'||@atlas_featurenumber"
        hideCoverage="0"/>
```
This is what is stored in the layout, we never modify neither the `coverageLayerSource`, nor the `coverageLayer` in the post-offline editing export phase.

**Comment by nirvn** [comment]
@suricactus , hm, quite odd that it stores the source on top of the layer reference. I'm wondering if it's merely a fallback in case the cover layer ID is invalid.

If so, the recent work I did on offline editing (which was backported to 3.20 here https://github.com/qgis/QGIS/commit/3a30bdb81f91d1b63d946f3a28b165cae1c1072d ) would fix this.

**Comment by suricactus** [comment]
Thanks. Have not looked into detail, I will manage to have time to look at it next month.

**Comment by suricactus** [comment]
I confirm this is comming with the next QGIS.
