### ISSUE TITLE
Re-adding 3.16 LTR support

### ISSUE THREAD

**Issue by nirvn** [opengisch/libqfieldsync#8]
This commit (https://github.com/opengisch/libqfieldsync/commit/796023459997688ecf2b321c50dafa399401c3d1) broke qfieldsync on the current QGIS LTR (3.16). We should aim to maintain LTR support as much as possible.

**Comment by suricactus** [comment]
I need to copy the tests from QFieldSync here, so we can catch such issues in advance.
